from __future__ import annotations

"""Curated vibe templates that ground playlist generation in human-authored intents."""

from dataclasses import dataclass
from typing import Dict, List, Sequence


@dataclass(frozen=True)
class VibeTemplate:
    id: str
    title: str
    description: str
    tags: Sequence[str]
    seed_genres: Sequence[str]
    targets: Dict[str, float]


VIBE_TEMPLATES: List[VibeTemplate] = [
    VibeTemplate(
        id="afro_safari_adventure",
        title="Afro Safari Adventure",
        description="Lively afrobeat rhythms and bold percussion for open-air drives through the savanna.",
        tags=["safari", "wildlife", "adventure", "madagascar", "africa", "roadtrip", "sunset"],
        seed_genres=["afrobeat", "world-music", "dancehall"],
        targets={
            "target_energy": 0.78,
            "target_valence": 0.7,
            "target_tempo": 116,
            "target_danceability": 0.66,
            "target_acousticness": 0.18,
        },
    ),
    VibeTemplate(
        id="malagasy_sunset_chill",
        title="Malagasy Sunset Chill",
        description="Warm guitar, island grooves, and gentle vocals inspired by Madagascar sunsets.",
        tags=["madagascar", "indian-ocean", "sunset", "island", "chill", "coast"],
        seed_genres=["world-music", "acoustic", "folk"],
        targets={
            "target_energy": 0.48,
            "target_valence": 0.62,
            "target_tempo": 96,
            "target_danceability": 0.52,
            "target_acousticness": 0.45,
        },
    ),
    VibeTemplate(
        id="savanna_star_gaze",
        title="Savanna Star Gaze",
        description="Nighttime ambient textures and slow tribal percussion beneath a wide-open sky.",
        tags=["savanna", "night", "stargaze", "ambient", "wildlife", "nature"],
        seed_genres=["ambient", "world-music", "sleep"],
        targets={
            "target_energy": 0.32,
            "target_valence": 0.48,
            "target_tempo": 78,
            "target_danceability": 0.34,
            "target_acousticness": 0.56,
        },
    ),
    VibeTemplate(
        id="tropical_beach_day",
        title="Tropical Beach Day",
        description="Sun-kissed tropical pop, breezy guitars, and steel drums for a bright seaside afternoon.",
        tags=["beach", "tropical", "vacation", "sunny", "island", "uplifting"],
        seed_genres=["latin", "dance", "reggaeton"],
        targets={
            "target_energy": 0.74,
            "target_valence": 0.82,
            "target_tempo": 118,
            "target_danceability": 0.78,
            "target_acousticness": 0.22,
        },
    ),
    VibeTemplate(
        id="caribbean_carnival",
        title="Caribbean Carnival",
        description="High-energy soca and dancehall for street parties and non-stop celebrations.",
        tags=["carnival", "caribbean", "festival", "party", "dance", "street"],
        seed_genres=["dancehall", "latin", "world-music"],
        targets={
            "target_energy": 0.9,
            "target_valence": 0.85,
            "target_tempo": 124,
            "target_danceability": 0.82,
            "target_acousticness": 0.12,
        },
    ),
    VibeTemplate(
        id="late_night_coding_flow",
        title="Late Night Coding Flow",
        description="Minimal electronic pulses and lo-fi textures that keep focus sharp deep into the night.",
        tags=["coding", "focus", "night", "late-night", "programming", "lofi"],
        seed_genres=["lo-fi", "minimal-techno", "ambient"],
        targets={
            "target_energy": 0.42,
            "target_valence": 0.5,
            "target_tempo": 82,
            "target_danceability": 0.42,
            "target_instrumentalness": 0.82,
        },
    ),
    VibeTemplate(
        id="deep_focus_ambient",
        title="Deep Focus Ambient",
        description="Sparse drones and evolving pads for uninterrupted concentration.",
        tags=["focus", "ambient", "concentration", "study", "work"],
        seed_genres=["ambient", "minimal-techno", "study"],
        targets={
            "target_energy": 0.3,
            "target_valence": 0.45,
            "target_tempo": 72,
            "target_danceability": 0.25,
            "target_instrumentalness": 0.9,
        },
    ),
    VibeTemplate(
        id="high_intensity_workout",
        title="High Intensity Workout",
        description="Explosive bass drops, commanding vocals, and relentless tempos to power tough workouts.",
        tags=["workout", "gym", "hiit", "intense", "training"],
        seed_genres=["edm", "electro", "work-out"],
        targets={
            "target_energy": 0.94,
            "target_valence": 0.6,
            "target_tempo": 135,
            "target_danceability": 0.76,
            "target_instrumentalness": 0.08,
        },
    ),
    VibeTemplate(
        id="boxing_gym_grit",
        title="Boxing Gym Grit",
        description="Hard-hitting hip-hop and aggressive beats for fight training.",
        tags=["boxing", "fighting", "gym", "training", "adrenaline"],
        seed_genres=["hip-hop", "edm", "hard-rock"],
        targets={
            "target_energy": 0.92,
            "target_valence": 0.44,
            "target_tempo": 132,
            "target_danceability": 0.65,
            "target_acousticness": 0.08,
        },
    ),
    VibeTemplate(
        id="sunny_road_trip",
        title="Sunny Road Trip",
        description="Upbeat indie and alt-pop singalongs built for long drives under blue skies.",
        tags=["roadtrip", "drive", "sunny", "open-road", "summer"],
        seed_genres=["road-trip", "indie-pop", "pop"],
        targets={
            "target_energy": 0.72,
            "target_valence": 0.78,
            "target_tempo": 112,
            "target_danceability": 0.64,
            "target_acousticness": 0.18,
        },
    ),
    VibeTemplate(
        id="mountain_trail_run",
        title="Mountain Trail Run",
        description="Pulsing electro and organic percussion to keep pace on rugged trails.",
        tags=["run", "trail", "mountain", "outdoor", "adventure"],
        seed_genres=["electronic", "edm", "world-music"],
        targets={
            "target_energy": 0.88,
            "target_valence": 0.62,
            "target_tempo": 128,
            "target_danceability": 0.7,
            "target_acousticness": 0.16,
        },
    ),
    VibeTemplate(
        id="cozy_coffee_shop",
        title="Cozy Coffee Shop",
        description="Gentle indie folk and mellow jazz for rainy-day cafés.",
        tags=["coffee", "cafe", "cozy", "rainy", "study", "reading"],
        seed_genres=["indie", "folk", "jazz"],
        targets={
            "target_energy": 0.42,
            "target_valence": 0.58,
            "target_tempo": 88,
            "target_danceability": 0.44,
            "target_acousticness": 0.52,
        },
    ),
    VibeTemplate(
        id="candlelit_dinner",
        title="Candlelit Dinner Jazz",
        description="Smooth jazz, soulful vocals, and lush strings for intimate evenings.",
        tags=["dinner", "romantic", "evening", "date", "jazz"],
        seed_genres=["jazz", "soul", "romance"],
        targets={
            "target_energy": 0.38,
            "target_valence": 0.7,
            "target_tempo": 82,
            "target_danceability": 0.36,
            "target_acousticness": 0.48,
        },
    ),
    VibeTemplate(
        id="late_night_neon_drive",
        title="Late Night Neon Drive",
        description="Retro synthwave and dreamy vocals for midnight cruises through neon cities.",
        tags=["night", "drive", "city", "neon", "retro", "synthwave"],
        seed_genres=["synth-pop", "electro", "indie-pop"],
        targets={
            "target_energy": 0.68,
            "target_valence": 0.54,
            "target_tempo": 110,
            "target_danceability": 0.6,
            "target_acousticness": 0.1,
        },
    ),
    VibeTemplate(
        id="berlin_warehouse_techno",
        title="Berlin Warehouse Techno",
        description="Dark, hypnotic techno for long nights in underground clubs.",
        tags=["techno", "warehouse", "berlin", "club", "underground", "rave"],
        seed_genres=["techno", "minimal-techno", "electro"],
        targets={
            "target_energy": 0.93,
            "target_valence": 0.34,
            "target_tempo": 128,
            "target_danceability": 0.74,
            "target_acousticness": 0.04,
        },
    ),
    VibeTemplate(
        id="latin_rooftop_party",
        title="Latin Rooftop Party",
        description="Modern Latin pop and reggaeton grooves meant for dance floors under the stars.",
        tags=["latin", "party", "dance", "rooftop", "night", "summer"],
        seed_genres=["latin", "reggaeton", "dance"],
        targets={
            "target_energy": 0.86,
            "target_valence": 0.84,
            "target_tempo": 120,
            "target_danceability": 0.82,
            "target_acousticness": 0.18,
        },
    ),
    VibeTemplate(
        id="brazilian_carnaval",
        title="Brazilian Carnaval",
        description="Explosive samba batucada and upbeat MPB anthems for parade season.",
        tags=["brazil", "carnaval", "festival", "samba", "parade"],
        seed_genres=["samba", "mpb", "latin"],
        targets={
            "target_energy": 0.92,
            "target_valence": 0.88,
            "target_tempo": 126,
            "target_danceability": 0.78,
            "target_acousticness": 0.28,
        },
    ),
    VibeTemplate(
        id="nostalgic_90s_rnb",
        title="Nostalgic 90s R&B",
        description="Smooth harmonies and slow jams from the golden era of R&B.",
        tags=["90s", "nostalgic", "rnb", "slow-jam", "throwback"],
        seed_genres=["r-n-b", "soul", "hip-hop"],
        targets={
            "target_energy": 0.52,
            "target_valence": 0.68,
            "target_tempo": 92,
            "target_danceability": 0.64,
            "target_acousticness": 0.22,
        },
    ),
    VibeTemplate(
        id="bedroom_pop_daydream",
        title="Bedroom Pop Daydream",
        description="Shimmering guitars and dreamy vocals for wistful afternoons.",
        tags=["bedroom", "dreamy", "indie", "daydream", "nostalgic"],
        seed_genres=["indie-pop", "chill", "synth-pop"],
        targets={
            "target_energy": 0.52,
            "target_valence": 0.66,
            "target_tempo": 102,
            "target_danceability": 0.58,
            "target_acousticness": 0.28,
        },
    ),
    VibeTemplate(
        id="epic_fantasy_quest",
        title="Epic Fantasy Quest",
        description="Cinematic orchestrations and sweeping choirs for grand adventures.",
        tags=["fantasy", "epic", "adventure", "orchestral", "quest"],
        seed_genres=["movies", "classical", "ambient"],
        targets={
            "target_energy": 0.72,
            "target_valence": 0.5,
            "target_tempo": 108,
            "target_danceability": 0.18,
            "target_acousticness": 0.62,
        },
    ),
    VibeTemplate(
        id="meditative_yoga",
        title="Meditative Yoga",
        description="Breath-paced meditative instrumentals for grounding yoga flows.",
        tags=["yoga", "meditation", "calm", "wellness", "breath"],
        seed_genres=["ambient", "new-age", "world-music"],
        targets={
            "target_energy": 0.26,
            "target_valence": 0.6,
            "target_tempo": 64,
            "target_danceability": 0.22,
            "target_instrumentalness": 0.92,
        },
    ),
    VibeTemplate(
        id="classical_study_session",
        title="Classical Study Session",
        description="Light piano and chamber works that aid sustained focus.",
        tags=["study", "focus", "piano", "classical", "reading"],
        seed_genres=["piano", "classical", "study"],
        targets={
            "target_energy": 0.28,
            "target_valence": 0.55,
            "target_tempo": 76,
            "target_danceability": 0.18,
            "target_instrumentalness": 0.95,
        },
    ),
    VibeTemplate(
        id="piano_sleep",
        title="Piano Sleep Serenade",
        description="Soft lullaby-like piano to wind down slowly.",
        tags=["sleep", "calm", "night", "relax", "bedtime"],
        seed_genres=["sleep", "piano", "ambient"],
        targets={
            "target_energy": 0.18,
            "target_valence": 0.48,
            "target_tempo": 60,
            "target_danceability": 0.18,
            "target_instrumentalness": 0.96,
        },
    ),
    VibeTemplate(
        id="gospel_sunday_morning",
        title="Gospel Sunday Morning",
        description="Joyful choirs and uplifting organ grooves for a hopeful start.",
        tags=["sunday", "morning", "gospel", "uplifting", "choir"],
        seed_genres=["gospel", "soul", "world-music"],
        targets={
            "target_energy": 0.7,
            "target_valence": 0.9,
            "target_tempo": 104,
            "target_danceability": 0.6,
            "target_acousticness": 0.36,
        },
    ),
    VibeTemplate(
        id="indie_campfire",
        title="Indie Campfire Night",
        description="Acoustic strums and hushed harmonies for stargazing by the fire.",
        tags=["campfire", "outdoor", "night", "acoustic", "friends"],
        seed_genres=["acoustic", "folk", "indie"],
        targets={
            "target_energy": 0.46,
            "target_valence": 0.64,
            "target_tempo": 88,
            "target_danceability": 0.42,
            "target_acousticness": 0.68,
        },
    ),
    VibeTemplate(
        id="melancholy_rain_walk",
        title="Melancholy Rain Walk",
        description="Laid-back indie and alt pop for reflective walks under grey skies.",
        tags=["rainy", "melancholy", "walk", "city", "reflective"],
        seed_genres=["indie", "alternative", "sad"],
        targets={
            "target_energy": 0.4,
            "target_valence": 0.38,
            "target_tempo": 86,
            "target_danceability": 0.42,
            "target_acousticness": 0.36,
        },
    ),
    VibeTemplate(
        id="confident_trap_bounce",
        title="Confident Trap Bounce",
        description="Swagger-heavy trap and hip-hop for high-energy confidence boosts.",
        tags=["confident", "swagger", "trap", "boss", "anthem"],
        seed_genres=["hip-hop", "r-n-b", "funk"],
        targets={
            "target_energy": 0.9,
            "target_valence": 0.58,
            "target_tempo": 138,
            "target_danceability": 0.76,
            "target_acousticness": 0.08,
        },
    ),
    VibeTemplate(
        id="summer_pool_party",
        title="Summer Pool Party",
        description="Sparkling dance-pop and tropical house perfect for backyard sunshine.",
        tags=["summer", "pool", "party", "daytime", "friends"],
        seed_genres=["dance", "edm", "pop"],
        targets={
            "target_energy": 0.88,
            "target_valence": 0.9,
            "target_tempo": 122,
            "target_danceability": 0.8,
            "target_acousticness": 0.2,
        },
    ),
    VibeTemplate(
        id="winter_fireplace_evening",
        title="Winter Fireplace Evening",
        description="Warm jazz trio pieces and gentle singer-songwriter tunes for cold nights indoors.",
        tags=["winter", "fireplace", "cozy", "evening", "warm"],
        seed_genres=["jazz", "acoustic", "folk"],
        targets={
            "target_energy": 0.38,
            "target_valence": 0.58,
            "target_tempo": 76,
            "target_danceability": 0.36,
            "target_acousticness": 0.6,
        },
    ),
    VibeTemplate(
        id="festival_sunrise_afterglow",
        title="Festival Sunrise Afterglow",
        description="Dreamy downtempo electronica for watching dawn after a long night.",
        tags=["festival", "sunrise", "afterhours", "chill", "downtempo"],
        seed_genres=["electronic", "ambient", "chill"],
        targets={
            "target_energy": 0.56,
            "target_valence": 0.54,
            "target_tempo": 98,
            "target_danceability": 0.6,
            "target_acousticness": 0.2,
        },
    ),
    VibeTemplate(
        id="urban_jazz_night",
        title="Urban Jazz Night",
        description="Modern jazz fusion and neo-soul grooves for stylish lounges.",
        tags=["city", "night", "jazz", "lounge", "cocktail"],
        seed_genres=["jazz", "soul", "r-n-b"],
        targets={
            "target_energy": 0.58,
            "target_valence": 0.6,
            "target_tempo": 102,
            "target_danceability": 0.58,
            "target_acousticness": 0.3,
        },
    ),
    VibeTemplate(
        id="calming_spa_day",
        title="Calming Spa Day",
        description="Soothing ambient and nature textures for peaceful retreats.",
        tags=["spa", "calm", "relax", "wellness", "self-care"],
        seed_genres=["ambient", "new-age", "sleep"],
        targets={
            "target_energy": 0.2,
            "target_valence": 0.5,
            "target_tempo": 62,
            "target_danceability": 0.2,
            "target_instrumentalness": 0.95,
        },
    ),
    VibeTemplate(
        id="street_food_night_market",
        title="Street Food Night Market",
        description="Global beats, funk, and future bass for buzzing night markets.",
        tags=["street-food", "market", "night", "city", "travel"],
        seed_genres=["world-music", "funk", "electronic"],
        targets={
            "target_energy": 0.8,
            "target_valence": 0.74,
            "target_tempo": 118,
            "target_danceability": 0.72,
            "target_acousticness": 0.22,
        },
    ),
    VibeTemplate(
        id="stormy_drama_orchestra",
        title="Stormy Drama Orchestra",
        description="Brooding strings and cinematic swells for dramatic storytelling.",
        tags=["storm", "drama", "cinematic", "dark", "intense"],
        seed_genres=["movies", "classical", "ambient"],
        targets={
            "target_energy": 0.7,
            "target_valence": 0.32,
            "target_tempo": 108,
            "target_danceability": 0.16,
            "target_acousticness": 0.7,
        },
    ),
    VibeTemplate(
        id="sunrise_gratitude",
        title="Sunrise Gratitude",
        description="Hopeful acoustic pop and gentle gospel touches to welcome the day.",
        tags=["sunrise", "morning", "hopeful", "gratitude", "uplifting"],
        seed_genres=["acoustic", "gospel", "pop"],
        targets={
            "target_energy": 0.58,
            "target_valence": 0.82,
            "target_tempo": 102,
            "target_danceability": 0.56,
            "target_acousticness": 0.4,
        },
    ),
]

